name: reflected_mustache
version: 1.0.11

author: Mike Mitterer <office@mikemitterer.at>
description: Mustache template library
homepage: https://github.com/MikeMitterer/relected_mustache

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  reflectable:
    ^4.0.5
    # path: /Volumes/Daten/DevLocal/DevDart/reflectable

  logging: ^1.2.0

dev_dependencies:
  test: ^1.24.3

  build_runner: ^2.3.3
  build_test: ^2.2.1
  build_web_compilers: ^3.2.7
